version: '3.9'
services:
  restaurant-management-api:
    container_name: restaurant-management-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: restaurant-management-api
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-restaurant-management-api:5432/restaurant_management_api_development
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgresql-restaurant-management-api
    restart: always

  postgresql-restaurant-management-api:
    image: postgres:15-alpine
    container_name: postgresql-restaurant-management-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_management_api_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: