CREATE TABLE restaurants (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL,
                       cooking VARCHAR(100),
                       street VARCHAR(255),
                       neighborhood VARCHAR(255),
                       zip_code VARCHAR(20),
                       city VARCHAR(100),
                       state VARCHAR(100),
                       number VARCHAR(20),
                       complement VARCHAR(255),
                       opening_at TIME,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       user_id BIGINT,
                       CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);
