CREATE TABLE menu_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(100) NOT NULL,
                             description VARCHAR(100),
                             price DECIMAL(10,2) NOT NULL,
                             photo_url VARCHAR(100),
                             dine_in BOOLEAN DEFAULT TRUE,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             restaurant_id BIGINT,
                             CONSTRAINT fk_user FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
);
